# Macro file for the initialization of example B4
# in interactive session
#
# Set some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4

#detectors and components
/lmon/construct/geometry ../config/geom_lowQ2.in
#/lmon/construct/geometry ../config/geom_all.in
#/lmon/construct/geometry ../config/geom_beamline.in
#/lmon/construct/geometry ../config/geom_test.in

#
# Initialize kernel
/run/initialize

#/lmon/input/tx/name /home/jaroslav/sim/lgen/data/lgen_beam_18_10kevt.tx
#/lmon/input/tx/name /home/jaroslav/sim/lgen/data/lgen_beam_18_beff2_10kevt.tx
/lmon/input/tx/name /home/jaroslav/sim/lgen/data/lgen_18x275_qr_Qb_beff2_1p2Mevt.tx

#/lmon/input/type pythia6
#/lmon/input/pythia6/name /home/jaroslav/sim/read_pythia/data/pythia_ep_18x275.txt
#/lmon/input/pythia6/name /home/jaroslav/sim/read_pythia/data/pythia_ep_18x275_Q2_0p1.txt
#/lmon/input/pythia6/select 2112
#/lmon/input/pythia6/select -211
#/lmon/input/pythia6/select 22

#/lmon/input/tx/name /home/jaroslav/sim/lgen/data/lgen_18x275_10p1Mevt.tx
#/lmon/input/tx/name /home/jaroslav/sim/lgen/data/lgen_18x275_qr_Qb_1p2Mevt.tx
#/lmon/input/tx/name /home/jaroslav/sim/lgen/data/lgen_18x275_0p1mrad_1p2Mevt_evt.dat
#/lmon/input/tx/select 22
#/lmon/input/tx/select 11

#
# Visualization setting
/control/execute vis.mac
