# Macro file for the initialization of example B4
# in interactive session
#
# Set some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 2
#

#detectors and components
#/lmon/construct/geometry config/geom_all.in
#/lmon/construct/geometry config/geom_beamline_18GeV.in
/lmon/construct/geometry config/geom_test.in

#input by particle gun
#/lmon/input/type gun
#/gun/energy 18 GeV
#/gun/particle e-
#/gun/direction 0 0 -1

#input by general particle source (GPS)
/lmon/input/type gps

/gps/verbose 2
/gps/particle neutron
/gps/number 1

/gps/ene/type Gauss
/gps/ene/mono  5.000 GeV
/gps/ene/sigma 0.0 GeV

/gps/pos/type Point
#/gps/pos/shape Cylinder
/gps/pos/centre 0.0 0.0 0.0 cm
#/gps/pos/radius 0.01 cm
#/gps/pos/halfz  10 cm
#/gps/ang/rot1 0 -0.025 0 radian
#/gps/ang/rot2 0 0 0
#/gps/position 0 0 0 cm

/gps/ang/type iso
#/gps/ang/rot1 -0.999688 0 -0.0249974
#/gps/ang/rot2  0 1 0 
/gps/ang/rot1 -1.0 0 0.0
/gps/ang/rot2  0 1 0

/gps/ang/mintheta  0.000 radian
/gps/ang/maxtheta  0.005 radian

/run/setCut 0.01 mm

#input from TParticle array
#/lmon/input/type tparticle
#/lmon/input/tparticle/name /home/jaroslav/sim/GETaLM_data/lumi/lumi_18x275_Lif_emin0p5_d200_beff3_5Mevt.root
#/lmon/input/tparticle/name /home/jaroslav/sim/GETaLM_data/beam/el_beam_18_t3p3_div202xy_1Mevt.root
#/lmon/input/tparticle/select 22
#/lmon/input/tparticle/select 11

#TX input
#/lmon/input/tx/name /home/jaroslav/sim/lgen/data/lgen_18x275_10p1Mevt.tx
#/lmon/input/tx/select 22

#HepMC3 input
#/lmon/input/type hepmc
#/lmon/input/hepmc/name /home/jaroslav/sim/GETaLM_data/beam/el_beam_18_t3p3_10kevt.hepmc

#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac

