
#run macro for EIC nodes

#detectors and components
#/lmon/construct/geometry ../config/geom_all.in
#/lmon/construct/geometry ../config/geom_lumi.in
#/lmon/construct/geometry ../config/geom_lowQ2.in
/lmon/construct/geometry ../config/geom_beamline.in

#init and run
/run/initialize

#input
#/lmon/input/type pythia6
#/lmon/input/pythia6/name /direct/eic+u/jadam/test/pythia6_example.txt
#/lmon/input/pythia6/select -211
#/lmon/input/pythia6/select 22

/lmon/input/tx/name /gpfs/mnt/gpfs02/eic/jadam/lgen/data/lgen_18x275_qr_Qb_beff2_1p2Mevt.tx
#/lmon/input/tx/name /gpfs/mnt/gpfs02/eic/jadam/lgen/data/lgen_beam_18_beff2_10p1Mevt.tx

#output
#/lmon/output/name ../data/lmon.root
#/lmon/output/name ../data/lmon_18x275_beff2_1Mevt.root
#/lmon/output/name /gpfs/mnt/gpfs02/eic/jadam/lmon/data/lmon_18x275_qr_Qb_beff2_Q3eR_1Mevt.root
#/lmon/output/name /gpfs/mnt/gpfs02/eic/jadam/lmon/data/lmon_18x275_beff2_1Mevt_v2.root
#/lmon/output/name /gpfs/mnt/gpfs02/eic/jadam/lmon/data/lmon_beam_18_beff2_10Mevt.root

#number of events
/run/beamOn 1000000

