
#Calorimetry visalization

/control/verbose 2
/control/saveHistory
/run/verbose 2
#

#detectors and components
/lmon/construct/geometry geom_calo.in

#input from TParticle array
#/lmon/input/type tparticle
#/lmon/input/tparticle/name /home/jaroslav/sim/GETaLM_data/lumi/lumi_18x275_Lif_emin0p5_d200_beff3_5Mevt.root
#/lmon/input/tparticle/select 22
#/lmon/input/tparticle/select 11

#TX input
#/lmon/input/tx/name /home/jaroslav/sim/lgen/data/lgen_18x275_10p1Mevt.tx
#/lmon/input/tx/select 22
#/lmon/input/tx/name /home/jaroslav/sim/lgen/data/lgen_beam_18_beff2_10kevt.tx
#/lmon/input/tx/name /home/jaroslav/sim/lgen/data/lgen_18x275_qr_Qb_beff2_1p2Mevt.tx
#/lmon/input/tx/name /home/jaroslav/sim/read_pythia/data/pythia_5M_beff2.tx

#pythia input
#/lmon/input/type pythia6

#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac
