
#detector
#/lmon/construct/geometry geom_pwo_cell.in
/lmon/construct/geometry geom_pwo_module.in

#input
/lmon/input/type gun
#/gun/energy 511 keV
#/gun/energy 100 keV
/gun/energy 10 MeV
#/gun/particle gamma
/gun/particle e-
/gun/position 0 0 1 mm
/gun/direction 0 0 -1

#output
/lmon/output/name pwo.root

#initialize and run
/run/initialize

#/process/optical/boundary/setInvokeSD true

/run/beamOn 1

